### ISSUE TITLE
msearch api body asking for object but examples are using an array

### ISSUE THREAD

**Issue by dhurley14** [elastic/elastic-client-generator#267]
## 💬 Questions and Help

The [type defined](https://github.com/elastic/elasticsearch-js/blob/master/api/types.d.ts#L7718-L7720) for the `msearch` api request is a `body` property typed as an object with nested `operations` but the [example docs](https://github.com/elastic/elasticsearch-js/blob/master/docs/examples/msearch.asciidoc) show the operations passed into the body property as an array of objects.

Curious which form is the expected format for the request? Do the docs need to be updated? Is the request typed incorrectly?

Thanks!

### Please note that this issue tracker is not a help forum and this issue may be closed.

It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

**Comment by delvedor** [comment]
Hello! The types are wrong, it should be a ndjson body :)
Thank you for reporting!

**Comment by dhurley14** [comment]
Great thanks!

**Comment by delvedor** [comment]
Closed in #318.
