### ISSUE TITLE
jsDoc metadata does not come through any longer

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elastic-client-generator#28]

**Comment by delvedor** [comment]
This is not a real issue, but rather a order problem.
A js doc comment it's parsed if it's defined before a decorator (or if there are no decorators at all).

For example, the following get parsed as expected.
```ts
/**
 * @foo bar
 */
@decorator('cool')
class FooBar {}
```
```ts
/**
 * @foo bar
 */
class FooBar {}
```
This one does not.
```ts
@decorator('cool')
/**
 * @foo bar
 */
class FooBar {}
```
