### ISSUE TITLE
Auto-generate kibana route schemas

### ISSUE THREAD

**Issue by jgowdyelastic** [elastic/elastic-client-generator#443]
ML provides kibana endpoint wrappers for every ML elasticsearch endpoint.
This means we need to maintain a collection of schemas to validate the endpoint arguments. These schemas are basically identical to types supplied by the elasticsearch client.

Would it be possible to have the endpoint request schemas auto-generated along with the types?

Having them autogenerated should also reduce the risk of discrepancies between the schemas and types when the client is updated.

An example of one of the ML schema files:
https://github.com/elastic/kibana/blob/master/x-pack/plugins/ml/server/routes/schemas/anomaly_detectors_schema.ts

**Comment by delvedor** [comment]
> Would it be possible to have the endpoint request schemas auto-generated along with the types?

Not sure I've understood 100% your question, but you can generate either code or directly JSON schema out of the [JSON specification](https://github.com/elastic/elastic-client-generator/blob/master/output/schema/schema.json?raw=true) we are producing in this repository.

**Comment by jgowdyelastic** [comment]
I was referring to the schema validation system kibana uses for the validation of data passed to the routes.
https://github.com/elastic/kibana/tree/master/packages/kbn-config-schema

But if this is not something which anyone else would use, then perhaps ML should look to generate these themselves.

One reason for having these autogenerated by the client is that they will remain in sync when the client updates its types.
I imagine there will be type clashes next time the version of the client is updated if there have been any changes to the ML types as the schemas will not have these changes.

**Comment by delvedor** [comment]
Given that this is very specific to Kibana, I won't ship it directly with the client, but I can help you building the automation for generating the validation schemas out of the specification we are producing.
We are planning to start branching soon, so it might be a good time to think about this :)

**Comment by jgowdyelastic** [comment]
After a chat with @delvedor we agreed that it will be better for ML to generate these schemas ourselves.
Closing this in favour of https://github.com/elastic/kibana/issues/99455
