### ISSUE TITLE
Additional model validations

### ISSUE THREAD

**Issue by swallez** [elastic/elastic-client-generator#45]
Validations we should add to the model parser/translater/exporter:

- [ ] Verify js_doc annotations: both their name (must be known) and their value (e.g. `@since` version format)
- [ ] Verify that path and query parameters in TS requests match those in the json rest spec.

**Comment by delvedor** [comment]
@swallez can we close this?

**Comment by swallez** [comment]
Yup, definitely! #169 does this and much more.
