### ISSUE TITLE
Rename nullable to required in InterfaceProperty

### ISSUE THREAD

**Issue by delvedor** [elastic/elastic-client-generator#51]
We should rename `nullable` to `required` in the `InterfaceProperty` definition, as semantically those two words are very different.
`nullable` means that a value can either have any type or null, while `required` indicates if a value must be defined or not.

```diff
  export class InterfaceProperty {
    name: string
    type: InstanceOf
-   nullable: boolean
+   required: boolean
```

**Comment by swallez** [comment]
+1 to clearly distinguish and disambiguate nullable ("that accepts `null` as a valid value") and required/optional ("may not be present" or "can be undefined").

However:

> `nullable` means that a value can either have any type or `null`

I guess you mean "have **a** type or be `null`" and this property will be defined using a union, e.g. `null | string`.

Let me give an example in Rust that does not have `null` nor undefined values to illustrate why a clear distinction is needed:

```rust
// Enums are Rust's union types
enum NullableString {
    Null,
    String(String)
}

struct Foo {
  required_non_nullable: String,
  required_nullable:     NullableString,
  optional_non_nullable: Option<String>,
  optional_nullale:      Option<NullableString>,
}
```
