### ISSUE TITLE
[QUESTION] Add `since` to spec?

### ISSUE THREAD

**Issue by philkra** [elastic/elastic-client-generator#8]
How about we add the since field to the TypeScript specification? It never really landed in the rest-api-spec and I suspect that it shouldn’t too hard to adjust https://github.com/elastic/clients-team/pull/93 to fit in a TS spec?

**Comment by Mpdreamz** [comment]
Stroke of brilliance! This would be a perfect home for it :+1:

**Comment by philkra** [comment]
assigning this to @delvedor
