### ISSUE TITLE
Add preamble to spec 

### ISSUE THREAD

**Issue by philkra** [elastic/elastic-client-generator#97]
Please add the following preamble to the generated [output/spec](https://github.com/elastic/elastic-client-generator/blob/master/output/schema/schema.json):

```json
{
"info": {
  "version": "x.y.z", 
  "title": "Elasticsearch Request & Response Specification", 
  "license": {
    "name": "Apache 2.0", 
    "url": "https://github.com/elastic/elastic-client-generator/blob/master/LICENSE"
  }
}
```

**Comment by Mpdreamz** [comment]
Rename to `_info` since the keys are sorted as noted by @delvedor
